[package]
name = "aarch64-std"
version = "0.1.0"
edition = "2021"

[features]
default = ["alloc"]
alloc = []

[dependencies]
aarch64-cpu = { git = "https://github.com/ccbrown/aarch64-cpu", rev = "db125991ee5ba515680f555f53475c5a0b6762d0" }
tock-registers = "0.8.0"
